implemented ability to save JSON report to file
dylang/npm-check pull request #400
Opened 2021-03-16 10:01 UTC by fumblehool

Fixes: #257 

`--json` flag will save json report to file.

Sample report:
```
[
    {
        "moduleName": "babel-runtime",
        "homepage": "https://github.com/babel/babel",
        "latest": "6.26.0",
        "installed": "6.26.0",
        "isInstalled": true,
        "notInstalled": false,
        "packageWanted": "6.26.0",
        "packageJson": "^6.6.1",
        "devDependency": false,
        "mismatch": false,
        "semverValid": "6.26.0",
        "easyUpgrade": true,
        "bump": null,
        "unused": false
    }
]
```

2021-04-20 17:27 UTC, sebastianrothe commented
Can this be merged, please ?

2022-07-24 09:50 UTC, Ephigenia commented
It is pretty common to support JSON format in a CLI tool. Usually this is done with the `--json` option and allows additional processing to the output and also storing, or even appending to files using POSIX pipe. I’d think if this PR is changed so that it only prints out the JSON it's totally fine. 

```
npx npm-check --json > my-report.json
```

And even processing would be easier, just imagine using [jq](https://stedolan.github.io/jq/) for filtering and processing:

```
npx npm-check --json | jq '.[] | {name: .modulename}'
```

With just printing the JSON it would become more flexible. If you’re interested there’s a pretty good chapter about output here: https://clig.dev/#output

2022-07-24 09:51 UTC, Ephigenia requested changes
Recommended change here to output JSON instead of writing to a file.

2023-04-30 15:53 UTC, fumblehool commented
closing this PR in-favour of PR: #532 cc @Ephigenia

2023-04-30 15:54 UTC, closed without merging